baseURL = "https://tjomk.github.io/"
languageCode = "en-us"
title = "We launch on Friday"
theme = "hugo-lithium-theme"
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[permalinks]
    blog = "/blog/:year/:month/:title"
    page = "/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    mainSections = ["blog"]

    description = ""

    favicon = "favicon.ico"

    [params.icon]
    url = "favicon.ico"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
